### ISSUE TITLE
relayd config

### ISSUE THREAD

**Issue by mischapeters** [httpoxy/httpoxy-org#10]
This should do the trick to protect anything behind OpenBSD relayd.

```
http protocol httpfilter {
        match request header remove "Proxy"
}
relay default {
        ...
        protocol httpfilter
        ...
}
```

**Comment by dominics** [comment]
Merged in a few hours ago. Should I add the `protocol httpfilter` bit, or is it common enough that "add it to an existing filter" is enough?

**Comment by mischapeters** [comment]
You can probably do it the way as you have done for Varnish, add [...] around it.
But it should be clear enough, at least I think. :)
